language: go

notifications:
  email: false

go:
    - "1.13"
    - master

before_install:
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - go get -u golang.org/x/lint/golint

install:
  - go build

script:
    - go test -v
    - golint -set_exit_status
